# Site settings
title: "Web development, jokes and electronics"
email: alexserverone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's talk about web development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexserver.me" # the base hostname & protocol for your site
twitter_username: alexserver
github_username:  alexserver

# Build settings
markdown: kramdown
